- name: MySQL ROLE | Add MySQL repository key
  apt_key: url=http://repo.mysql.com/RPM-GPG-KEY-mysql state=present
  become: true

- name: MySQL ROLE | Adding mysql sources.list deb url
  lineinfile: dest=/etc/apt/sources.list line="deb http://repo.mysql.com/apt/debian/ {{ ansible_distribution_release }} mysql-{{ mysql_version }}"
  become: true

- name: MySQL ROLE | Adding mysql sources.list deb-src url
  lineinfile: dest=/etc/apt/sources.list line="deb-src http://repo.mysql.com/apt/debian/ {{ ansible_distribution_release }} mysql-{{ mysql_version }}"
  become: true

- name: MySQL ROLE | Updating apt cache
  apt:
    update_cache: yes
  become: true

- name: MySQL ROLE | Install MySQL
  apt: name={{ item }} force=yes
  with_items:
   - python-mysqldb
   - mysql-server
  become: true

- name: MySQL ROLE | Update mysql root password for all root accounts
  mysql_user:
   name: root
   host: "{{ item }}"
   password: "{{ default_mysql_root_password }}"
   login_user: root
   login_password: "{{ default_mysql_root_password }}"
   check_implicit_admin: yes
   priv: "*.*:ALL,GRANT"
  with_items:
    - localhost

- name: MySQL ROLE | Add mysql default user
  mysql_user:
   name: "{{ default_mysql_user_login }}"
   host: "{{ item }}"
   password: "{{ default_mysql_user_password }}"
   login_user: root
   login_password: "{{ default_mysql_root_password }}"
   check_implicit_admin: yes
   priv: "*.*:ALL,GRANT"
  with_items:
    - "%"
    - localhost

- template:
    src: ../templates/etc/mysql/my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  become: true
  tags: mysql_copy_template
  notify: restart mysql service

#- name: MySQL ROLE | Ensure mysql is restarted
#  action: service name=mysql state=restarted
#  become: true
